name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image:  ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}
          tags: hive-3.1.2
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

  test_hive:
    needs: push_to_registry
    name: Test Hive server and metastore 
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Start all containers via docker-compose
        run: docker-compose up -d
        
      - name: Wait for hive-server to be up since it has the longest chain of dependencies
        run: docker run willwill/wait-for-it localhost:10000 -- echo "Hive server is up"

      - name: Test hiveserver2
        run: docker exec -it hive-server /opt/hive/bin/hive --service hiveserver2
        
      - name: Test Hive metastore
        run: docker exec -it hive-server /opt/hive/bin/hive --service metastore      

